
on:
  push:
    branches:
      - master
  pull_request:
      branches:
      - master
  schedule:
    - cron: '25 0,4,8,12,16,20 * * *'

name: CI fetch.build => vercel

jobs:
  build:
    name: build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: yarn install --pure-lockfile
        name: install deps

      - run: yarn  build --log-pages
        name: build app
        env:
          NODE_ENV: production
          

#   deploy:
#     needs: build
#     name: deploy to Vercel
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: amondnet/vercel-action@v20
#         with:
#           vercel-token: ${{ secrets.VERCEL_TOKEN }}
#           github-token: ${{ secrets.ACCESS_TOKEN }}
#           vercel-args: '--prod'
#           vercel-org-id: ${{ secrets.ORG_ID}}
#           vercel-project-id: ${{ secrets.PROJECT_ID}}
#           working-directory: ./
