# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1      
      with:           node-version: 12

      - run: yarn install --pure-lockfile
       name: install deps

       - run: yarn  build 
